# Enable Rotary Encoders
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Re-route the Left Encoder Pins to match the 42Keebs PCB routing paths
# (Standard Sofle uses pins that clash with your board's trace layout)
CONFIG_ZMK_REVERSE_ENCODERS=n

# Force Enable Power Management Features
CONFIG_ZMK_PM_SOFT_OFF=y
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000
